[project]
name = "depre-buddy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.122.0",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
